# Generated by Django 5.0.3 on 2024-03-25 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=150, verbose_name='место')),
                ('time', models.TimeField(default='12:00:00', verbose_name='время')),
                ('date', models.DateField(blank=True, null=True, verbose_name='дата')),
                ('action', models.CharField(max_length=100, verbose_name='действие')),
                ('is_pleasant', models.BooleanField(default=False, verbose_name='признак приятной привычки')),
                ('reward', models.CharField(blank=True, max_length=250, null=True, verbose_name='вознаграждение')),
                ('duration', models.PositiveIntegerField(blank=True, null=True, verbose_name='длительность выполнения')),
                ('periodicity', models.IntegerField(blank=True, default=1, null=True, verbose_name='периодичность')),
                ('is_public', models.BooleanField(default=False, verbose_name='признак публичности')),
            ],
            options={
                'verbose_name': 'привычка',
                'verbose_name_plural': 'привычки',
            },
        ),
    ]
